// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ivrzybpdpyoitldcxaqv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml2cnp5YnBkcHlvaXRsZGN4YXF2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3MjEwOTEsImV4cCI6MjA3MjI5NzA5MX0.StW3CpNkEWyh2EnzKHTqObKcv14sY5LGRdX_kL1Wo-0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});